#!/usr/bin/env python3
"""Higgsfield over its own API. NOT PART OF THE WORKFLOW — there is no key.

Damon, 2026-09-14: *"we do not have a higgsfield key so remove that from this
workflow entirely."*

This file was written for a key pair that was never issued, so every command
in it fails at `key()` and always has. Nothing in the lane calls it: plates
are prepared by `plates.py prepare`, generated by a session through the
Higgsfield MCP, and brought back by `plates.py ingest`.

It is kept, unwired, only so that the API shape does not have to be worked
out again if a key ever exists. Treat it as notes, not as a tool.

    Authorization: Key <KEY_ID>:<KEY_SECRET>
    submit  POST <path>                 -> {request_id, status_url}
    poll    GET  /requests/{id}/status  -> queued|in_progress|completed|failed
    result  images: [{url}]
"""

import argparse, json, subprocess, sys, time, urllib.error, urllib.request
from pathlib import Path

BASE = "https://platform.higgsfield.ai"
TERMINAL = {"completed", "failed", "nsfw", "canceled"}

# Text-to-image and reference-driven edit. The edit path is the one that keeps
# a batch consistent: corrections feed the approved frame back in rather than
# re-rolling the whole picture.
GENERATE = "/higgsfield-ai/nano-banana-pro/text-to-image"
EDIT = "/higgsfield-ai/nano-banana-pro/edit"


def _keychain(service, account="damon"):
    r = subprocess.run(["security", "find-generic-password",
                        "-s", service, "-a", account, "-w"],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ""


def key():
    """The Authorization header value, or None. Never printed, never logged."""
    kid = _keychain("higgsfield-key-id")
    sec = _keychain("higgsfield-key-secret")
    if not (kid and sec):
        env = Path.home() / ".workflow-worker.env"
        if env.is_file():
            vals = {}
            for line in env.read_text().splitlines():
                if "=" in line and not line.lstrip().startswith("#"):
                    k, v = line.split("=", 1)
                    vals[k.strip()] = v.strip().strip('"').strip("'")
            kid = kid or vals.get("HIGGSFIELD_KEY_ID", "")
            sec = sec or vals.get("HIGGSFIELD_KEY_SECRET", "")
    if not (kid and sec):
        return None
    return f"Key {kid}:{sec}"


def api(path, payload=None, method=None):
    auth = key()
    if not auth:
        sys.exit(
            "No Higgsfield API key on this machine.\n"
            "Create one at https://higgsfield.ai/settings/api then store it:\n"
            "  security add-generic-password -s higgsfield-key-id "
            "-a damon -w '<key id>'\n"
            "  security add-generic-password -s higgsfield-key-secret "
            "-a damon -w '<key secret>'")
    url = path if path.startswith("http") else BASE + path
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url, data=data, method=method or ("POST" if data else "GET"),
        headers={"Authorization": auth, "Accept": "application/json",
                 "Content-Type": "application/json",
                 # Their edge rejects a bare urllib agent with a 403 that looks
                 # exactly like a bad key. It is not one.
                 "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:400]
        sys.exit(f"Higgsfield {e.code} on {path}\n{body}")


def wait(request_id, timeout=600):
    """Poll to a terminal state. Returns the image urls."""
    start = time.time()
    while time.time() - start < timeout:
        s = api(f"/requests/{request_id}/status")
        status = s.get("status")
        if status in TERMINAL:
            if status != "completed":
                return None, status
            imgs = s.get("images") or s.get("result", {}).get("images") or []
            return [i["url"] for i in imgs if i.get("url")], status
        time.sleep(4)
    return None, "timeout"


def fetch(url, dest):
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=120) as r, open(dest, "wb") as f:
        f.write(r.read())
    return dest


def generate(prompt, aspect="4:5", refs=None):
    """One picture. Refs are Element ids, already embedded in the prompt as
    <<<id>>> — that is how Higgsfield carries an identity, so a caller does
    not pass them separately."""
    payload = {"prompt": prompt, "aspect_ratio": aspect}
    if refs:
        payload["image_reference_url"] = refs
    r = api(GENERATE, payload)
    rid = r.get("request_id") or r.get("id")
    return wait(rid)


def edit(image_url, change, aspect="4:5"):
    """A correction. The approved frame goes back in and ONE thing moves.

    This is the whole reason the API path matters: a fresh text-to-image roll
    re-rolls the face, the type and the layout along with the fix. Four ads
    once took eleven passes for exactly that reason."""
    prompt = ("Keep this image exactly as it is — same people, same faces, same "
              "layout, same type, same colours, same composition. Change ONLY "
              "the following, and nothing else: " + change)
    r = api(EDIT, {"prompt": prompt, "aspect_ratio": aspect,
                   "image_reference_url": [image_url]})
    rid = r.get("request_id") or r.get("id")
    return wait(rid)


def run_spec(spec_path, out_dir):
    """Every ad in a batch spec, straight into the finisher's inbox."""
    spec = json.loads(Path(spec_path).read_text())
    out = Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    made, failed = [], []
    for ad in spec["ads"]:
        pf = Path(spec_path).parent / "prompts" / f"{ad['slug']}.txt"
        if not pf.is_file():
            failed.append((ad["slug"], "no prompt file")); continue
        urls, status = generate(pf.read_text(),
                                aspect=ad.get("aspect", "4:5"))
        if not urls:
            failed.append((ad["slug"], status)); continue
        fetch(urls[0], out / f"{ad['slug']}.png")
        made.append(ad["slug"])
        print(f"  ✓ {ad['slug']}")
    for slug, why in failed:
        print(f"  ✗ {slug} — {why}")
    return made, failed


def main():
    # Refuse at the door rather than failing four frames in with a key error.
    print("hf.py is not part of the workflow — there is no Higgsfield API key.\n"
          "  prepare the plates:  tools/plates.py prepare --run <run>\n"
          "  generate them:       a session, through the Higgsfield MCP\n"
          "  bring them back:     tools/plates.py ingest --run <run> --results <f>\n"
          "See PIPELINE.md.")
    raise SystemExit(2)


def _main_unwired():
    a = argparse.ArgumentParser()
    sub = a.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check")
    g = sub.add_parser("generate"); g.add_argument("--spec", required=True); g.add_argument("--out", required=True)
    e = sub.add_parser("edit")
    e.add_argument("--image-url", required=True); e.add_argument("--change", required=True)
    e.add_argument("--out", required=True); e.add_argument("--aspect", default="4:5")
    o = a.parse_args()

    if o.cmd == "check":
        if not key():
            print("no key stored — see the header of this file")
            return
        me = api("/v1/me") if False else None   # no cheap whoami documented
        urls, status = generate("a single plain grey square on white, no text", "1:1")
        print("key works, generation returned:", status if not urls else "an image")
    elif o.cmd == "generate":
        made, failed = run_spec(o.spec, o.out)
        print(f"\n{len(made)} generated, {len(failed)} failed")
    elif o.cmd == "edit":
        urls, status = edit(o.image_url, o.change, o.aspect)
        if not urls:
            sys.exit(f"edit failed: {status}")
        print(fetch(urls[0], o.out))


if __name__ == "__main__":
    main()
